engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false        
ratings:
  paths:
  - src/**
exclude_paths:
- spec/**/*
- docs/**/*
