version: "2" 
plugins:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
exclude_patterns:
- docs/**/*
- "**/spec/**/*"
- "**/*.d.ts"
