engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
ratings:
  paths:
  - packages/casl-ability/src/**
  - packages/casl-angular/src/**
  - packages/casl-aurelia/src/**
  - packages/casl-mongoose/src/**
  - packages/casl-react/src/**
  - packages/casl-vue/src/**
exclude_paths:
- **/spec/**/*
- docs/**/*
