language: node_js
node_js:
  - "4.0.0"
  - "6.11.3"
  - "8.4.0"

before_install:
  - if [[ `npm -v` = 2* ]]; then npm i -g npm@3.10.8; fi

before_script:
  - npm run build

after_success:
  -  npm run coverage.submit
