language: node_js
node_js:
  - 6 # to be removed 2019-04-01
  - lts/*
  - node

cache:
  directories:
    - ./node_modules
    - ./packages/*/node_modules

before_install:
  - if [[ `npm -v` = 2* ]]; then npm i -g npm@3.10.8; fi

before_script:
  - npm run build
  - npm run bootstrap

script:
  - npm test -- --coverage

after_success:
  -  npm run coverage.submit
