language: node_js
node_js:
  - 6 # to be removed 2019-04-01
  - lts/*
  - node

cache:
  directories:
    - ./node_modules
    - ./packages/*/node_modules

before_script:
  - npm run build
  - npm run bootstrap

script:
  - WITH_COVERAGE=1 npm test

after_success:
  -  npm run coverage.submit
