title: CASL
description: CASL is an isomorphic authorization JavaScript library
show_downloads: false
baseurl: /casl
theme: jekyll-theme-architect
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: compressed
twitter_username: stalniy
gitter_url: https://gitter.im/stalniy-casl/casl?utm_source=docs&utm_medium=docs&utm_campaign=pr-docs&utm_content=docs
so_url: https://stackoverflow.com/questions/tagged/casl
