name: Docs

on:
  push:
    branches: [master]
    paths:
      - docs-src/**/*
      - .github/workflows/docs.yml

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CASL_VERSION: 4
    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: casl-docs-deps
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('docs-src/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install deps
      working-directory: docs-src
      run: npm install
    - name: Build documentation
      working-directory: docs-src
      env:
        LIT_APP_PUBLIC_PATH: "/v${{ env.CASL_VERSION }}"
        NODE_ENV: production
      run: LIT_APP_COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA") npm run build
    - name: Deploy
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_ACTOR: docs
      run: |
        CASL_DOCS_ROOT="./v${CASL_VERSION/.*/}"
        cat <<- EOF > $HOME/.netrc
          machine github.com
          login $GITHUB_ACTOR
          password $GITHUB_TOKEN
          machine api.github.com
          login $GITHUB_ACTOR
          password $GITHUB_TOKEN
        EOF
        chmod 600 $HOME/.netrc
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git fetch origin gh-pages
        git checkout -f gh-pages
        rm -rf $CASL_DOCS_ROOT
        mv docs-src/dist $CASL_DOCS_ROOT
        git add .
        git commit -m "chore(release): deploy ${CASL_DOCS_ROOT}"
        git push --set-upstream origin gh-pages
