name: CI

on: 
  push:
    paths: 
    - '**/*.js'
    - '**/*.ts'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node: 
          - 10 # 2020-04-01
          - 12
          - latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dev dependencies
      run: npm ci
    - name: Install dependencies and cross link packages
      run: npm run bootstrap
    - name: Build
      run: npm run build
    - name: lint & test
      run: WITH_COVERAGE=1 npm test
    - name: submit coverage
      env:
        CODECOV_TOKEN: "{{ secrets.CODECOV_TOKEN }}"
      run: npm run coverage.submit
