name: CI

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/main.yml
      - packages/**/*.{js,ts,json}
      - '*.{json,js}'
      - .eslintrc
      - tools/**/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16 # 2023-09-11
          - 18 # 2025-04-30
          - latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v1.2.1
      with:
        version: 8.4.0
    - name: Cache dependencies
      uses: actions/cache@v3
      env:
        cache-name: casl-deps
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm run -r --filter '[${{ github.event.pull_request.base.sha }}]' build
    - name: lint
      run: pnpm run -r --filter '[${{ github.event.pull_request.base.sha }}]' lint
    - name: test
      run: pnpm run -r --filter '[${{ github.event.pull_request.base.sha }}]' test -- --coverage
    - name: submit coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: pnpm run coverage.submit
