name: CI

on:
  push:
    branches: [master]
    paths:
    - .github/**/*
    - packages/**/*.{js,ts,json}
    - '*.{json,js}'
    - .eslintrc
    - tools/**/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 10 # 2020-04-01
          - 12
          - latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v1.2.0
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm recursive run build
    - name: lint & test
      run: |
        pnpm recursive run lint
        WITH_COVERAGE=1 pnpm recursive run test
    - name: submit coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: pnpm run coverage.submit
