name: Release packages
on:
  pull_request:
    types: [closed, labeled]

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'released')
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}
        run: |
          changed_packages=$(gh pr view --json files --jq '.files.[].path' "${{ github.event.pull_request.number }}" | cut -d / -f 1,2 | uniq)
          pnpm_options=(-r)
          for path in $changed_packages; do
            pnpm_options[${#pnpm_options[@]}]="--filter ./${path}"
          done
          echo "pnpm run ${pnpm_options[@]} release"
